### ISSUE TITLE
Issues with Typescript .env

### ISSUE THREAD

**Issue by twhite96** [twhite96/plausible-hit-counter#6]
Figure out how to use `process.env.NODE_ENV` in Typescript. I've already installed `@types/node`

**Comment by vimal-oneway** [comment]
https://github.com/twhite96/plausible-hit-counter/blob/715b6b605d0d5b761a759ef619bb8b8d09c52ea8/.env.example#L4
env varibales must start with VITE_variable_name

**Comment by twhite96** [comment]
> https://github.com/twhite96/plausible-hit-counter/blob/715b6b605d0d5b761a759ef619bb8b8d09c52ea8/.env.example#L4
> 
> env varibales must start with VITE_variable_name
> 
> 
Ok. I'll need to look at the Vite docs for this. Thanks

**Comment by twhite96** [comment]
Done
